name: Build Docker image

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
