name: Build Docker image

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if files are present
        run: ls -la
      - name: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
